name: Build and Release (aliaume attempt)

on:
  workflow_dispatch:

jobs:
  build_and_upload:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: |
          npm install
        working-directory: ./
          
      - name: Build Electron App
        run: |
          npm run make
        working-directory: ./

      - name: List directory contents (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          ls -R ./out/make
        shell: bash

      - name: Compress directory
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            7z a my_directory.zip  out/make/squirrel.windows/x64/Slajdomat-*.exe 
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            mv ./out/make/zip/darwin/arm64/*zip my_directory.zip
          else
            zip -r my_directory.zip ./out/
          fi
        shell: bash
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: "*.zip"
