name: Build the app


on: workflow_dispatch

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: |
        npm install
      working-directory: ./

    - name: Build Electron App
      run: |
        npm run make
      working-directory: ./

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: electron-app
        path: ./out
