name: Build and Release

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
                node-version: '20' 

        - name: Get version
          id: get_version
          run: |
                echo "::set-output name=version::$(node -p "require('./package.json').version")"
            
        - name: Install dependencies
          run: |
                npm install
          working-directory: ./
            
        - name: Build Electron App
          run: |
                npm run make
          working-directory: ./

        - name: Compress directory
          run: |
                if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
                    Compress-Archive -Path ./out/* -DestinationPath my_directory.zip
                else
                    zip -r my_directory.zip ./out/
                fi

        - name: Create Release
          id: create_release
          if: matrix.os == 'ubuntu-latest'
          uses: actions/create-release@v1
          env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
                tag_name: Automatic build ${{ steps.get_version.outputs.version }} 
                release_name: Release ${{ steps.get_version.outputs.version }}
                draft: true
                prerelease: false

        - name: Upload Release Asset
          id: upload_release_asset
          uses: actions/upload-release-asset@v1
          env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
                upload_url: ${{ steps.create_release.outputs.upload_url }}
                asset_path: ./my_directory.zip
                asset_name: my_directory-${{ matrix.os }}.zip
                asset_content_type: application/zip