name: test releasing

on:
    workflow_dispatch:

jobs:
    upload:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Create an empty hello.txt file
          run: touch hello.txt

        - name: Get release
          id: get_release
          uses: jossef/action-latest-release-info@v1.2.2

        - name: Upload Release Asset
          id: upload_release_asset
          uses: actions/upload-release-asset@v1
          env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
                upload_url: ${{ steps.get_release.outputs.upload_url }}
                asset_path: ./hello.txt
                asset_name: hello.txt
                asset_content_type: text/plain