name: Create and Upload File to Latest Release

on:
  workflow_dispatch:

jobs:
  create-and-upload-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get latest release
      id: latest_release
      run: |
        token=$TOKEN
        url="https://api.github.com/repos/${{ github.repository }}/releases/latest"
        upload_url=$(curl -sSL -H "Authorization: token $token" $url | jq -r '.upload_url')
        upload_url="${upload_url%\{*}"
        echo "::set-output name=upload_url::$upload_url"

    - name: Create empty file
      run: touch hello.txt

    - name: Upload file to release
      run: |
        token=$TOKEN
        upload_url="${{ steps.latest_release.outputs.upload_url }}?name=hello.txt"
        curl -sSL -X POST -H "Authorization: token $token" -H "Content-Type: application/octet-stream" --data-binary @hello.txt $upload_url
