name: Create and Upload File to Latest Release

on:
  workflow_dispatch:

jobs:
  create-and-upload-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create empty file
      run: touch hello.txt

    - name: Upload hello to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: hello.txt
        asset_name: mything
        tag: ${{ github.ref }}
        overwrite: true
        body: "This is my release text"
