name: test releasing

on:
    workflow_dispatch:

jobs:
    upload:
        runs-on: ubuntu-latest
        steps:
        - name: Create an empty hello.txt file
          run: touch hello.txt

        - name: Get Current Release
          id: get_current_release
          uses: joutvhu/get-release@v1
          with:
            tag_name : latest
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Upload Release Asset
          id: upload_release_asset
          uses: actions/upload-release-asset@v1
          env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
                upload_url: ${{ steps.get_current_release.outputs.upload_url }}
                asset_path: ./hello.txt
                asset_name: hello.txt
                asset_content_type: text/plain
